package br.com.bradesco.coredigital.api.automation.enums;

import lombok.Getter;

@Getter
public enum ProjectType {

    //Financings Supply
    FINANCINGS_CONTRACT_SUPPLY("FINANCINGS_CONTRACT_SUPPLY"),
    FINANCINGS_LIST_SUPPLY("FINANCINGS_LIST_SUPPLY"),
    FINANCINGS_INSTALLMENT_SUPPLY("FINANCINGS_INSTALLMENT_SUPPLY"),
    FINANCINGS_PAYMENT_SUPPLY("FINANCINGS_PAYMENT_SUPPLY"),
    FINANCINGS_WARRANTY_SUPPLY("FINANCINGS_WARRANTY_SUPPLY"),

    //Financings Core
    FINANCINGS_CONTRACT_CORE("FINANCINGS_CONTRACT_CORE"),
    FINANCINGS_LIST_CORE("FINANCINGS_LIST_CORE"),
    FINANCINGS_INSTALLMENT_CORE("FINANCINGS_INSTALLMENT_CORE"),
    FINANCINGS_PAYMENT_CORE("FINANCINGS_PAYMENT_CORE"),
    FINANCINGS_WARRANTY_CORE("FINANCINGS_WARRANTY_CORE"),

    //Loans Supply
    LOANS_CONTRACT_SUPPLY("LOANS_CONTRACT_SUPPLY"),
    LOANS_LIST_SUPPLY("LOANS_LIST_SUPPLY"),
    LOANS_INSTALLMENT_SUPPLY("LOANS_INSTALLMENT_SUPPLY"),
    LOANS_PAYMENT_SUPPLY("LOANS_PAYMENT_SUPPLY"),
    LOANS_WARRANTY_SUPPLY("LOANS_WARRANTY_SUPPLY"),

    //Loans Core
    LOANS_CONTRACT_CORE("LOANS_CONTRACT_CORE"),
    LOANS_LIST_CORE("LOANS_LIST_CORE"),
    LOANS_INSTALLMENT_CORE("LOANS_INSTALLMENT_CORE"),
    LOANS_PAYMENT_CORE("LOANS_PAYMENT_CORE"),
    LOANS_WARRANTY_CORE("LOANS_WARRANTY_CORE"),

    //CWS LOANS_FINANCINGS
    CWS_LOANS_FINANCINGS_CHES("CWS_LOANS_FINANCINGS_CHES"),
    CWS_LOANS_FINANCINGS_CRIM("CWS_LOANS_FINANCINGS_CRIM"),
    CWS_LOANS_FINANCINGS_EMPF("CWS_LOANS_FINANCINGS_EMPF"),
    CWS_LOANS_FINANCINGS_EMPG("CWS_LOANS_FINANCINGS_EMPG"),
    CWS_LOANS_FINANCINGS_GRAN("CWS_LOANS_FINANCINGS_GRAN"),

    //PRE-CONSENT
    PRE_CONSENT("PRE_CONSENT"),

    //GSEG
    GSEG("GSEG"),

    //Account Supply
    ACCOUNT_LIST_SUPPLY("ACCOUNT_LIST_SUPPLY"),
    ACCOUNT_IDENTIFICATION_SUPPLY("ACCOUNT_IDENTIFICATION_SUPPLY"),
    ACCOUNT_BALANCE_SUPPLY("ACCOUNT_BALANCE_SUPPLY"),
    ACCOUNT_TRANSACTION_SUPPLY("ACCOUNT_TRANSACTION_SUPPLY"),
    ACCOUNT_LIMIT_SUPPLY("ACCOUNT_LIMIT_SUPPLY"),

    //Account Core
    ACCOUNT_LIST_CORE("ACCOUNT_LIST_CORE"),
    ACCOUNT_IDENTIFICATION_CORE("ACCOUNT_IDENTIFICATION_CORE"),
    ACCOUNT_BALANCE_CORE("ACCOUNT_BALANCE_CORE"),
    ACCOUNT_TRANSACTION_CORE("ACCOUNT_TRANSACTION_CORE"),
    ACCOUNT_LIMIT_CORE("ACCOUNT_LIMIT_CORE"),

    //Account Resources

    ACCOUNT_RESOURCES("ACCOUNT_RESOURCES"),

    //CWS
    ACCOUNT_LIST_CWS("ACCOUNT_LIST_CWS"),
    ACCOUNT_IDENTIFICATION_CWS("ACCOUNT_IDENTIFICATION_CWS"),
    ACCOUNT_TRANSACTION_TYPE_CWS("ACCOUNT_TRANSACTION_TYPE_CWS"),

    //ADPOS Supply
    UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_SUPPLY("UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_SUPPLY"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_SUPPLY("UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_SUPPLY"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_SUPPLY("UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_SUPPLY"),

    //ADPOS Core
    UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_CORE("UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_CORE"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_CORE("UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_CORE"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_CORE("UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_CORE"),

    //ADPOS Cws
    UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_CWS("UNARRANGED_ACCOUNTS_OVERDRAFT_LIST_CWS"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_CWS("UNARRANGED_ACCOUNTS_OVERDRAFT_CONTRACT_CWS"),
    UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_CWS("UNARRANGED_ACCOUNTS_OVERDRAFT_PAYMENT_CWS"),

    //DCOM Supply
    INVOICE_FINANCINGS_CONTRACT_SUPPLY("INVOICE_FINANCINGS_CONTRACT_SUPPLY"),
    INVOICE_FINANCINGS_LIST_SUPPLY("INVOICE_FINANCINGS_LIST_SUPPLY"),
    INVOICE_FINANCINGS_INSTALMENT_SUPPLY("INVOICE_FINANCINGS_INSTALMENT_SUPPLY"),
    INVOICE_FINANCINGS_PAYMENT_SUPPLY("INVOICE_FINANCINGS_PAYMENT_SUPPLY"),

    //DCOM Core
    INVOICE_FINANCINGS_LIST_CORE("INVOICE_FINANCINGS_LIST_CORE"),
    INVOICE_FINANCINGS_CONTRACT_CORE("INVOICE_FINANCINGS_CONTRACT_CORE"),
    INVOICE_FINANCINGS_INSTALMENT_CORE("INVOICE_FINANCINGS_INSTALMENT_CORE"),

    //DCOM Cws
    INVOICE_FINANCINGS_LIST_CWS("INVOICE_FINANCINGS_LIST_CWS"),
    INVOICE_FINANCINGS_CONTRACT_CWS("INVOICE_FINANCINGS_LIST_CWS"),
    INVOICE_FINANCINGS_INSTALMENT_CWS("INVOICE_FINANCINGS_INSTALMENT_CWS"),

    //Card Supply
    CARD_LIST_SUPPLY("CARD_LIST_SUPPLY"),
    CARD_IDENTIFICATION_SUPPLY("CARD_IDENTIFICATION_SUPPLY"),
    CARD_BILL_SUPPLY("CARD_BILL_SUPPLY"),
    CARD_LIMIT_SUPPLY("CARD_LIMIT_SUPPLY"),
    CARD_TRANSACTION_SUPPLY("CARD_TRANSACTION_SUPPLY"),
    CARD_INVOICE_TRANSACTION_SUPPLY("CARD_INVOICE_TRANSACTION_SUPPLY"),

    //Card Egrees
    CARD_LIST_EGREES("CARD_LIST_EGREES"),
    CARD_IDENTIFICATION_EGREES("CARD_IDENTIFICATION_EGREES"),
    CARD_BILL_EGREES("CARD_BILL_EGREES"),
    CARD_LIMITS_EGREES("CARD_LIMITS_EGREES"),
    CARD_TRANSACTION_EGREES("CARD_TRANSACTION_EGREES"),
    CARD_INVOICE_TRANSACTION_EGREES("CARD_INVOICE_TRANSACTION_EGREES"),

    //REGISTRATION DATA SUPPLY
    REGISTRATION_DATA_AGORA_SUPPLY("REGISTRATION_DATA_AGORA_SUPPLY"),
    REGISTRATION_DATA_BRADESCARD_SUPPLY("REGISTRATION_DATA_BRADESCARD_SUPPLY"),
    REGISTRATION_DATA_BRADESCO_OR_NEXT_SUPPLY("REGISTRATION_DATA_BRADESCO_OR_NEXT_SUPPLY"),
    REGISTRATION_DATA_LOSANGO_OR_BF_SUPPLY("REGISTRATION_DATA_LOSANGO_OR_BF_SUPPLY"),

    //REGISTRATION DATA CORE
    REGISTRATION_DATA_AGORA_CORE("REGISTRATION_DATA_AGORA_CORE"),
    REGISTRATION_DATABRADESCO_OR_NEXT_CORE("REGISTRATION_DATABRADESCO_OR_NEXT_CORE"),

    //EGREES TOKEN
    CARD_TOKEN_EGREES("CARD_TOKEN_EGREES"),

    //Card Egrees Losango
    CARD_LIST_LOSANGO_EGREES("CARD_LIST_EGREES"),
    CARD_IDENTIFICATION_LOSANGO_EGREES("CARD_IDENTIFICATION_EGREES"),
    CARD_BILL_LOSANGO_EGREES("CARD_BILL_EGREES"),
    CARD_LIMITS_LOSANGO_EGREES("CARD_LIMITS_EGREES"),
    CARD_TRANSACTION_LOSANGO_EGREES("CARD_TRANSACTION_EGREES"),
    CARD_INVOICE_TRANSACTION_LOSANGO_EGREES("CARD_INVOICE_TRANSACTION_EGREES");

    private String projectType;

    ProjectType(String projectType) {

        this.projectType = projectType;
    }
}